-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-03-04 17:35:45 CST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

CREATE TABLE DIM_TRANSACTION
  (
    transaction_id   INTEGER NOT NULL ,
    transaction_name VARCHAR2 (128)
  ) ;
ALTER TABLE DIM_TRANSACTION ADD CONSTRAINT DIM_TRANSACTION_PK PRIMARY KEY ( transaction_id ) ;


CREATE TABLE FCT_TEST_RESULT
  (
    result_id                    INTEGER NOT NULL ,
    user_action_time             INTEGER ,
    dom_ready_time		         INTEGER ,
    transaction_id 				 INTEGER NOT NULL
  ) ;
ALTER TABLE FCT_TEST_RESULT ADD CONSTRAINT FCT_TEST_RESULT_PK PRIMARY KEY ( result_id ) ;


ALTER TABLE FCT_TEST_RESULT ADD CONSTRAINT DIM_TRANSACTION_FKn FOREIGN KEY ( transaction_id ) REFERENCES DIM_TRANSACTION ( transaction_id ) ;



